using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcRugby.Models
{
    public class Team
    {
        [Required]
        [Key]
        public int TeamId { get; set; } // Autogenerated Id
        public string? SrCompetitorId {get; set;} // Provided by 3rd party Api, to prevent duplicate entries
        public string? TeamName { get; set; } // E.g.: Munster, Edinburgh, Ireland, Scotland etc.
        public string? Country { get; set; } // E.g.: Munster, Edinburgh, Ireland, Scotland etc.

        // CHILD ENTITY RELATIONSHIPS

        // Setup relationship with Player
        public List<Player>? Players { get; set; } // Reference navigation property

        // Setup relationship with Team Lineups
        public List<TeamLineup>? TeamLineups { get; set; } // Reference navigation property
    }
}