using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RugbyDataApi.Models
{
    public class PlayerLineup
    {
        [Required]
        [Key]
        public int PlayerLineupId { get; set; } // Autogenerated Id

    }
}