using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RugbyDataApi.Models
{
    public class TeamLineup
    {
        [Required]
        [Key]
        public int TeamLineupId { get; set; } // Autogenerated Id

        public string? Designation { get; set; } // e.g.: Home or Away
        // PARENT ENTITY RELATIONSHIPS

        // Setup relationship with Fixture
        [Required]
        [ForeignKey("FixtureId")]
        public int FixtureId { get; set; } // ForeignKey
        public Fixture? Fixture { get; set; } // Reference navigation property
        
        [Required]
        [ForeignKey("TeamId")]
        // Setup relationship with Team
        public int TeamId { get; set; } // ForeignKey
        public Team? Team { get; set; } // Reference navigation property

        // CHILD ENTITY RELATIONSHIPS

        // Setup relationship with Player
        public List<Player>? Players { get; set; } // Reference navigation property
    }
}